### ISSUE TITLE
Empty primary key

### ISSUE THREAD

**Issue by petranden** [jamband/yii2-schemadump#11]
There is a possibility that a table, usually is a join table, does not have a primary key at all. In this case it will respond with an exception of offset because it tries to get pk[0] of null $pk. You should change the corresponding line on actionCreate to check if it has primary key, then to call the function getPrimaryKeyDefinition. 

if (!empty($table->primaryKey)) $stdout .= $this->getPrimaryKeyDefinition($table->primaryKey, $stdout, $offset);

**Comment by jamband** [comment]
Thank you for find a bug!
