### ISSUE TITLE
42000: 1064 Syxtax error occured while deploying migrations

### ISSUE THREAD

**Issue by CCSS-Github** [jamband/yii2-schemadump#12]
First of all, its excellent library. It save alot of my time hats off to you.

While following the process suggested by you. I am able to create migrations scripts successfully. But when I try to deploy it via yii command line utility its gave me error of 1064 syntax error and process aborted

**Comment by CCSS-Github** [comment]
After spending some time, I figure out its escaping issue in one of my table there is single qoutes in comments which breaks your script and gave syntax error which i handle via this \' fixes my problem

**Comment by jamband** [comment]
It contains some quote character in the column of the comment?
Like `user's` `'user' column`

**Comment by CCSS-Github** [comment]
Thanks dear, appreciated
