### ISSUE TITLE
Can't load package via composer

### ISSUE THREAD

**Issue by Vetrinus** [jamband/yii2-schemadump#17]
[Composer\Repository\InvalidRepositoryException]                             
  No valid bower.json was found in any branch or tag of https://github.com/jq  
  uery/jquery-dist.git, could not load a package from it.

**Comment by jamband** [comment]
Please tell me the command you executed.
(e.g. `composer require --dev --prefer-dist jamband/yii2-schemadump "*"`)

Also please tell me the contents of composer.json.

**Comment by Vetrinus** [comment]
I have no idea what exactly happened, but now this works. Sorry
